# Generated by Django 5.0.6 on 2024-06-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
